theme: jekyll-theme-dinky
title: PoC .NET Framework - GitHub Actions CI pipeline
description: 🔬 Proof of Concept of a .NET Framework project using GitHub Actions for build, testing and deploy
show_downloads: true
