theme: jekyll-theme-dinky
title: POC GitHub Actions .NET Framework - Continuous Integration
description: A proof of concept of a .NET Framework project using GitHub Actions for build, testing and deploy
show_downloads: true
