name: Test webhook

on:
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

      - name: Webhook
        uses: distributhor/workflow-webhook@v3
        env:
          verbose: true
          webhook_type: 'json-extended'
          webhook_url: 'https://webhook.site/83b82504-2e39-48e6-9e1b-93bb9ff12fd1'
          webhook_secret: '{"x-github-release-token": "123456789"}'
          data: '{ "run_number":  ${{ github.run_number }},  "downloadUrls": ["url#1", "url#2", "url#3"]}'
          event_name: 'release'

  
